language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:
  - mvn clean install sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=e87a4a9074f0dbd0ffc1aeb887f179b6bff0a38f

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false
